-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-securepoll_msgs-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX spmsg_entity;
ALTER TABLE  securepoll_msgs
ADD  PRIMARY KEY (msg_entity, msg_lang, msg_key);