-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ../../extensions/SecurePoll/sql/securepoll_log.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE securepoll_log (
  spl_id SERIAL NOT NULL,
  spl_timestamp TIMESTAMPTZ NOT NULL,
  spl_election_id INT NOT NULL,
  spl_user INT NOT NULL,
  spl_type SMALLINT NOT NULL,
  spl_target INT DEFAULT NULL,
  PRIMARY KEY(spl_id)
);

CREATE INDEX spl_timestamp ON securepoll_log (spl_timestamp);
