-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-securepoll_properties-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX sppr_entity;
CREATE TEMPORARY TABLE /*_*/__temp__securepoll_properties AS
SELECT  pr_entity,  pr_key,  pr_value
FROM  /*_*/securepoll_properties;
DROP  TABLE  /*_*/securepoll_properties;
CREATE TABLE  /*_*/securepoll_properties (    pr_entity INTEGER NOT NULL,    pr_key BLOB NOT NULL,    pr_value BLOB NOT NULL,    PRIMARY KEY(pr_entity, pr_key)  );
INSERT INTO  /*_*/securepoll_properties (pr_entity, pr_key, pr_value)
SELECT  pr_entity,  pr_key,  pr_value
FROM  /*_*/__temp__securepoll_properties;
DROP  TABLE /*_*/__temp__securepoll_properties;