-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-securepoll_msgs-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX spmsg_entity;
CREATE TEMPORARY TABLE /*_*/__temp__securepoll_msgs AS
SELECT  msg_entity,  msg_lang,  msg_key,  msg_text
FROM  /*_*/securepoll_msgs;
DROP  TABLE  /*_*/securepoll_msgs;
CREATE TABLE  /*_*/securepoll_msgs (    msg_entity INTEGER NOT NULL,    msg_lang BLOB NOT NULL,    msg_key BLOB NOT NULL,    msg_text CLOB NOT NULL,    PRIMARY KEY(msg_entity, msg_lang, msg_key)  );
INSERT INTO  /*_*/securepoll_msgs (    msg_entity, msg_lang, msg_key, msg_text  )
SELECT  msg_entity,  msg_lang,  msg_key,  msg_text
FROM  /*_*/__temp__securepoll_msgs;
DROP  TABLE /*_*/__temp__securepoll_msgs;