-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/securepoll_entity (
  en_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  en_type BLOB NOT NULL
);


CREATE TABLE /*_*/securepoll_properties (
  pr_entity INTEGER NOT NULL, pr_key BLOB NOT NULL,
  pr_value BLOB NOT NULL
);

CREATE UNIQUE INDEX sppr_entity ON /*_*/securepoll_properties (pr_entity, pr_key);


CREATE TABLE /*_*/securepoll_questions (
  qu_entity INTEGER NOT NULL,
  qu_election INTEGER NOT NULL,
  qu_index INTEGER NOT NULL,
  PRIMARY KEY(qu_entity)
);

CREATE INDEX spqu_election_index ON /*_*/securepoll_questions (qu_election, qu_index, qu_entity);


CREATE TABLE /*_*/securepoll_options (
  op_entity INTEGER NOT NULL,
  op_election INTEGER NOT NULL,
  op_question INTEGER NOT NULL,
  PRIMARY KEY(op_entity)
);

CREATE INDEX spop_question ON /*_*/securepoll_options (op_question, op_entity);

CREATE INDEX spop_election ON /*_*/securepoll_options (op_election);


CREATE TABLE /*_*/securepoll_lists (
  li_name BLOB DEFAULT NULL, li_member INTEGER NOT NULL
);

CREATE INDEX splists_name ON /*_*/securepoll_lists (li_name, li_member);

CREATE INDEX splists_member ON /*_*/securepoll_lists (li_member, li_name);


CREATE TABLE /*_*/securepoll_log (
  spl_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  spl_timestamp BLOB NOT NULL, spl_election_id INTEGER NOT NULL,
  spl_user INTEGER UNSIGNED NOT NULL,
  spl_type SMALLINT UNSIGNED NOT NULL,
  spl_target INTEGER UNSIGNED DEFAULT NULL
);

CREATE INDEX spl_timestamp ON /*_*/securepoll_log (spl_timestamp);
