-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-securepoll_properties-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX sppr_entity ON  /*_*/securepoll_properties;
ALTER TABLE  /*_*/securepoll_properties
ADD  PRIMARY KEY (pr_entity, pr_key);