-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ../../extensions/SecurePoll/sql/securepoll_log.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/securepoll_log (
  spl_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  spl_timestamp BINARY(14) NOT NULL,
  spl_election_id INT NOT NULL,
  spl_user INT UNSIGNED NOT NULL,
  spl_type TINYINT UNSIGNED NOT NULL,
  spl_target INT UNSIGNED DEFAULT NULL,
  INDEX spl_timestamp (spl_timestamp),
  PRIMARY KEY(spl_id)
) /*$wgDBTableOptions*/;
