-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/securepoll_entity (
  en_id INT AUTO_INCREMENT NOT NULL,
  en_type VARBINARY(32) NOT NULL,
  PRIMARY KEY(en_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/securepoll_properties (
  pr_entity INT NOT NULL,
  pr_key VARBINARY(32) NOT NULL,
  pr_value MEDIUMBLOB NOT NULL,
  UNIQUE INDEX sppr_entity (pr_entity, pr_key)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/securepoll_questions (
  qu_entity INT NOT NULL,
  qu_election INT NOT NULL,
  qu_index INT NOT NULL,
  INDEX spqu_election_index (qu_election, qu_index, qu_entity),
  PRIMARY KEY(qu_entity)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/securepoll_options (
  op_entity INT NOT NULL,
  op_election INT NOT NULL,
  op_question INT NOT NULL,
  INDEX spop_question (op_question, op_entity),
  INDEX spop_election (op_election),
  PRIMARY KEY(op_entity)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/securepoll_lists (
  li_name VARBINARY(255) DEFAULT NULL,
  li_member INT NOT NULL,
  INDEX splists_name (li_name, li_member),
  INDEX splists_member (li_member, li_name)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/securepoll_log (
  spl_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  spl_timestamp BINARY(14) NOT NULL,
  spl_election_id INT NOT NULL,
  spl_user INT UNSIGNED NOT NULL,
  spl_type TINYINT UNSIGNED NOT NULL,
  spl_target INT UNSIGNED DEFAULT NULL,
  INDEX spl_timestamp (spl_timestamp),
  PRIMARY KEY(spl_id)
) /*$wgDBTableOptions*/;
